name: CSD318 Lab 3 Pipeline 

on: [push] 

jobs: 

  Build: 

    runs-on: ubuntu-latest 

    steps: 

      - name: Check out repository code 

        uses: actions/checkout@v6 

      - run: echo "Build step complete." 

  

  Test: 

    needs: Build 

    runs-on: ubuntu-latest 

    steps: 

      - run: echo "Running automated tests..." 

      - run: echo "All tests passed."

  

  Deploy: 

    needs: Test 

    runs-on: ubuntu-latest 

    steps: 

      - run: echo "Deploying to production!" 
